### PR TITLE
Resolves #3 : Adding clang-format check target to CMake.

### LINKED ISSUE #3: Add clang-format check as a CMake target
We have a [.clang-format](https://github.com/FoundationDB/fdb-document-layer/blob/master/.clang-format) style file committed to the repo. All commits should make sure they follow the style. We should have a CMake target that fails if the format is not good. This will make it easy to enforce.

### PR DESCRIPTION
**Pull request by apkar**
Also adding docker-compose service for the sake of CI.

### CODE REVIEW

**Comment by apkar** [comment]
cc @dongxinEric

**Comment by AlvinMooreSr** [comment]
test this please

**Comment by apkar** [comment]
test this please

**Comment by apkar** [comment]
test this please

**Comment by AlvinMooreSr** [comment]
test this please

**Pull request merged**
